spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-billowing-frost-a1hqvqhl.ap-southeast-1.pg.koyeb.app/koyebdb
spring.datasource.username=lumi-adm
spring.datasource.password=kw3MfapnWo7L
spring.datasource.driver-class-name=org.postgresql.Driver

#DATABASE DEV


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true

server.port = 8080
server.servlet.context-path=/api

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT
security.jwt.secret-key=90blwCqJS9jqHORniIxsCwmoCmhhszbOSxjvAZG92KM=
security.jwt.expiration-time=43200000

# Swagger
openapi.dev-url=http://localhost:8080
openapi.prod-url=https://backend-dev-synrgy-team4.koyeb.app
springdoc.swagger-ui.path=/swagger-ui.html

# Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= affudina663@gmail.com
spring.mail.password=dwkqqguwghvvrypl
spring.mail.sender.name=admin
spring.mail.sender.mail=no-reply-@test.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

expired.token.password.minute=30

springdoc.swagger-ui.path=/swagger-ui.html
